<% project_name = 'eq-music-api' %>

default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>

development:
  <<: *default
  database: <%= project_name %>_development

production:
  <<: *default
  database: <%= project_name %>_production
